# Site settings
title: Software Development
email: johann.walder@outlook.com
description: > #
url: "https://johannwalder.com"
twitter_username: johannwalder
github_username:  johannwalder
linkedin_username:  johannwalder

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true

google_analytics: UA-89445038-1

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md